"""The frozen engine, asserted in the suite rather than in a script nobody runs.

`scripts/gen_golden.py --check` can compare, but a script that CI never invokes
protects nothing — and the six existing determinism tests all call the estimator
twice in one process on one list, so a change that shifts every published print
by 50 bp, deterministically and reproducibly, passes all of them green.

This is the test that fails instead. When it does, read the diff: if the move is
intended, `make golden` in the SAME commit and name the numbers that moved in the
message. Re-blessing is a decision, not a chore.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "scripts"))

# The same `capture()` the generator uses, imported rather than reimplemented —
# a test that computes the baseline its own way is testing its own copy.
from gen_golden import REL_TOL, capture, moved_fields  # noqa: E402

GOLDEN = _ROOT / "tests" / "golden" / "estimator.json"


@pytest.fixture(scope="module")
def frozen() -> dict:
    if not GOLDEN.exists():  # pragma: no cover - only before the first capture
        pytest.skip("no golden baseline yet — run `make golden`")
    return json.loads(GOLDEN.read_text())


@pytest.fixture(scope="module")
def fresh() -> dict:
    return capture()


def test_the_engine_reproduces_its_frozen_output(frozen, fresh):
    """Every recorded field, per index, to the recorded precision."""
    moved = moved_fields(frozen, fresh)
    assert moved == [], (
        "the engine's published output moved:\n  "
        + "\n  ".join(moved)
        + "\n\nIf this is deliberate, run `make golden` in the same commit and say "
        "which numbers moved and why."
    )


def test_the_baseline_records_the_scenario_that_produced_it(frozen):
    """A golden file whose scenario is not written down is a number with no
    provenance — it cannot be regenerated by anyone who did not write it."""
    assert frozen["scenario"] == {"seed": 5, "horizon": 3600.0, "events_per_service": 2500}
    assert frozen["digits"] == 12
    assert set(frozen["indices"]) == {"ACR-INF", "ACR-GPU", "ACR-DATA"}


def test_the_baseline_pins_the_numbers_that_actually_reach_the_chain(frozen):
    """A golden that recorded only diagnostics would pass while the print moved."""
    for index_id, row in frozen["indices"].items():
        for key in ("value", "ci_lo", "ci_hi", "attack_cost_per_bp", "n_obs"):
            assert key in row, f"{index_id} baseline is missing {key}"
        assert row["ci_lo"] <= row["value"] <= row["ci_hi"], index_id
        assert row["attack_cost_per_bp"] > 0, index_id
        assert row["n_obs"] > 0, index_id


def test_the_tolerance_still_catches_an_engine_change(frozen):
    """A tolerance is a knob, and an unguarded knob is how a golden goes decorative.

    `moved_fields` compares floats by relative difference because exact equality
    across two numpy builds is not a property anything can hold — CI pins Python
    3.11, this machine runs 3.13, and `max_cluster_influence_bp` differed in the
    12th decimal on all three indices. But a tolerance loose enough to absorb that
    must still be far too tight to absorb a real change, so both directions are
    asserted here rather than assumed.
    """
    base = frozen["indices"]["ACR-INF"]["attack_cost_per_bp"]

    # The arrival-order bug this file was built to find moved this figure 37%.
    assert moved_fields(frozen, {"indices": {"ACR-INF": {"attack_cost_per_bp": base * 1.37}}})

    # A 1% change is still a regression, not noise.
    assert moved_fields(frozen, {"indices": {"ACR-INF": {"attack_cost_per_bp": base * 1.01}}})

    # The cross-build last-bit difference that actually occurred, scaled up 10x,
    # is still absorbed — so CI and this machine agree about the engine.
    nudged = base * (1 + REL_TOL / 10)
    assert moved_fields(frozen, {"indices": {"ACR-INF": {"attack_cost_per_bp": nudged}}}) == []

    # Integers are exact: one fewer observation IS the engine changing.
    n = frozen["indices"]["ACR-INF"]["n_obs"]
    assert moved_fields(frozen, {"indices": {"ACR-INF": {"n_obs": n - 1}}})
