"""The frozen engine, asserted in the suite rather than in a script nobody runs.

`scripts/gen_golden.py --check` can compare, but a script that CI never invokes
protects nothing — and the six existing determinism tests all call the estimator
twice in one process on one list, so a change that shifts every published print
by 50 bp, deterministically and reproducibly, passes all of them green.

This is the test that fails instead. When it does, read the diff: if the move is
intended, `make golden` in the SAME commit and name the numbers that moved in the
message. Re-blessing is a decision, not a chore.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "scripts"))

# The same `capture()` the generator uses, imported rather than reimplemented —
# a test that computes the baseline its own way is testing its own copy.
from gen_golden import capture  # noqa: E402

GOLDEN = _ROOT / "tests" / "golden" / "estimator.json"


@pytest.fixture(scope="module")
def frozen() -> dict:
    if not GOLDEN.exists():  # pragma: no cover - only before the first capture
        pytest.skip("no golden baseline yet — run `make golden`")
    return json.loads(GOLDEN.read_text())


@pytest.fixture(scope="module")
def fresh() -> dict:
    return capture()


def test_the_engine_reproduces_its_frozen_output(frozen, fresh):
    """Every recorded field, per index, to the recorded precision."""
    moved: list[str] = []
    for index_id, row in fresh["indices"].items():
        prev = frozen["indices"].get(index_id)
        assert prev is not None, f"{index_id} is missing from the baseline"
        for key, value in row.items():
            if prev.get(key) != value:
                moved.append(f"{index_id}.{key}: {prev.get(key)} -> {value}")
    assert moved == [], (
        "the engine's published output moved:\n  "
        + "\n  ".join(moved)
        + "\n\nIf this is deliberate, run `make golden` in the same commit and say "
        "which numbers moved and why."
    )


def test_the_baseline_records_the_scenario_that_produced_it(frozen):
    """A golden file whose scenario is not written down is a number with no
    provenance — it cannot be regenerated by anyone who did not write it."""
    assert frozen["scenario"] == {"seed": 5, "horizon": 3600.0, "events_per_service": 2500}
    assert frozen["digits"] == 12
    assert set(frozen["indices"]) == {"ACR-INF", "ACR-GPU", "ACR-DATA"}


def test_the_baseline_pins_the_numbers_that_actually_reach_the_chain(frozen):
    """A golden that recorded only diagnostics would pass while the print moved."""
    for index_id, row in frozen["indices"].items():
        for key in ("value", "ci_lo", "ci_hi", "attack_cost_per_bp", "n_obs"):
            assert key in row, f"{index_id} baseline is missing {key}"
        assert row["ci_lo"] <= row["value"] <= row["ci_hi"], index_id
        assert row["attack_cost_per_bp"] > 0, index_id
        assert row["n_obs"] > 0, index_id
