import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/* The archived bundle may describe the paywall. It may not name the gate.
 *
 * MEASURED ON THE LIVE SITE 2026-10-10: the front page read `LIVE · DEV GATE`
 * in gold over the production Circle paywall. Both presses report
 * `facilitator: "circle"` — I checked `/health` and `/x402/info` on each — but
 * `/api/console` gives the press 2.5 seconds and falls back to
 * `lib/fallback.json`, whose `x402.facilitator` is `"dev"`. True when that
 * bundle was cut; false now. So a Render cold start turned "I could not ask"
 * into a confident, downward claim about the product, on the first load after
 * idle — which is the most common first impression there is.
 *
 * It was not only cosmetic: `ApiConsole`'s `agentAllowed` keys on
 * `mode === "dev"`, so the same stale value changed what the console offered.
 *
 * A SOURCE SCAN, because the thing being held is a negative — that one field
 * does not reach the client from the archive — and there is no running press in
 * CI to prove it against. Same mechanism as `coverage.test.ts` and
 * `chainWiring.test.ts`.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

test("the bundled x402 section still carries the stale gate, which is why this gate exists", () => {
  /* Pinned deliberately. If someone later edits the bundle's value to
     "circle", the route below must STILL drop it — a corrected guess is the
     same mistake with a luckier value, and the bundle is regenerated by a
     script that has written the wrong chain's data before. */
  const bundle = JSON.parse(readFileSync(join(ROOT, "lib", "fallback.json"), "utf8")) as {
    x402?: { facilitator?: string };
  };
  assert.equal(
    bundle.x402?.facilitator,
    "dev",
    "if this changed, re-read the comment above before relaxing anything",
  );
});

test("the console route drops the gate when it serves the archive", () => {
  const src = readFileSync(join(ROOT, "app", "api", "console", "route.ts"), "utf8");
  // The fallback must destructure `facilitator` away rather than spread the
  // section whole.
  assert.match(
    src,
    /facilitator:\s*_gate,\s*\.\.\.rest/,
    "the archived x402 section must have `facilitator` removed before it is sent",
  );
  assert.ok(
    !/data:\s*bundleSection\(chain,\s*"x402"\)\s*\?\?\s*null/.test(src),
    "the raw bundled section must not be the response body: it names a gate that is not live",
  );
});

test("the type admits the third state, so absence is expressible", () => {
  const src = readFileSync(join(ROOT, "lib", "types.ts"), "utf8");
  assert.match(
    src,
    /facilitator\?:\s*"dev"\s*\|\s*"circle"/,
    '"we could not ask" is a real answer and the type has to allow it',
  );
});

test("nothing renders a gate badge without a value, and the demo agent stays shut", () => {
  const src = readFileSync(join(ROOT, "components", "ApiConsole.tsx"), "utf8");
  // `{mode && (…)}` — absent mode draws nothing at all.
  assert.match(src, /\{mode && \(/, "an absent facilitator must render no badge rather than a default one");
  // And the demo agent is gated on a POSITIVE dev reading, never on "not circle".
  assert.match(
    src,
    /agentAllowed\s*=\s*gateLive && mode === "dev"/,
    "the demo agent must require a confirmed dev gate, so an unknown one withholds it",
  );
});
