"use client";

import { Ed } from "@/components/Ed";
import { UNITS, isUnit, INDEX_FOR_UNIT, type Unit } from "@/lib/indices";
import { WhyEmpty } from "@/components/WhyEmpty";
import { rateChip } from "@/lib/rateChip";
import { useParCheck } from "@/lib/useLive";
import type { ParCheck, ParQuote } from "@/lib/types";
import { useEffect, useState } from "react";

/* Bring your own bill.
 *
 * `/par` has always answered a stranger's invoice with no onboarding, and
 * `lib/endpoints.ts` has always advertised it as runnable. What a reader could
 * not do was USE it: the only way to exercise it was to hand-build a query
 * string with a percent-encoded `$/1k tokens` in it.
 *
 * This page is evidence, not a funnel. There is nothing to sign up for and
 * nothing is captured. The thing it is trying to earn is one specific kind of
 * trust: that the comparison is against somebody else's published prices and
 * that you can go and look at them. So every row carries its own link, and the
 * state of the basket those prices came from is stated on the page rather than
 * implied by a verdict.
 */

const ADDRESS = /^0x[0-9a-fA-F]{40}$/;

/* The repository is public and `anchors/GAP.md` is committed, generated by
   `make anchors-report` and ratchet-checked by `make anchors-check` — so it is
   a durable third-party-checkable artifact rather than a page we can quietly
   edit. Verified reachable (HTTP 200) before being linked. */
const GAP_URL = "https://github.com/kaustubh76/ACR---Arc-Compute-Rate/blob/main/anchors/GAP.md";

/** What each unit means in a sentence, because `$/1k tokens` is only obvious
 *  if you already know which market you are in. */
const UNIT_HINT: Record<Unit, { x: string; p: string }> = {
  "$/1k tokens": {
    x: "Inference, priced per thousand tokens on a blended 75/25 prompt to completion read.",
    p: "AI text work. The price of a thousand tokens.",
  },
  "$/GPU-sec": {
    x: "Rented compute, priced per GPU-second from published hourly list rates.",
    p: "Renting a graphics card. The price of one second.",
  },
  "$/MB": {
    x: "Metered egress, priced per megabyte at first-tier public list price.",
    p: "Moving data out. The price of one megabyte.",
  },
};

function fmtUsd(n: number | null | undefined): string {
  if (n == null || !Number.isFinite(n)) return "…";
  if (n === 0) return "0";
  // Six significant figures, not a fixed width: these numbers run from
  // 0.000002 to 4.00, and a fixed two decimals renders most of them as 0.00.
  // The same mistake once gave ACR-DATA's mid and ask two significant figures
  // and printed them identically.
  return n.toPrecision(6).replace(/\.?0+$/, "");
}

function fmtBp(n: number | null | undefined): string {
  if (n == null || !Number.isFinite(n)) return "…";
  return `${n >= 0 ? "+" : ""}${n.toFixed(0)} bp`;
}


function Form({
  unit,
  billed,
  quantity,
  vendor,
  onUnit,
  onBilled,
  onQuantity,
  onVendor,
  onSubmit,
  problem,
  busy,
}: {
  unit: Unit;
  billed: string;
  quantity: string;
  vendor: string;
  onUnit: (u: Unit) => void;
  onBilled: (v: string) => void;
  onQuantity: (v: string) => void;
  onVendor: (v: string) => void;
  onSubmit: () => void;
  problem: string | null;
  busy: boolean;
}) {
  const hint = UNIT_HINT[unit];
  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        onSubmit();
      }}
    >
      {/* A segmented group, because `.segmented button.on` is this
          stylesheet's own selected state and three mutually exclusive choices
          are what it is for. `aria-pressed` makes the choice audible. */}
      <div className="segmented" role="group" aria-label="what you are buying">
        {UNITS.map((u) => (
          <button
            key={u}
            type="button"
            className={u === unit ? "on" : ""}
            aria-pressed={u === unit}
            onClick={() => onUnit(u)}
          >
            {u}
          </button>
        ))}
      </div>
      <p className="standfirst">
        <Ed x={hint.x} p={hint.p} />
      </p>

      {/* Inputs take NO className: globals.css styles them by element selector
          on purpose, because "this is a vocabulary, not a component, and no
          .tsx should have to opt in". */}
      <div className="btn-row">
        <label className="label">
          <Ed x="What you were billed, in USDC" p="What the bill says, in dollars" />
          <br />
          <input
            type="text"
            inputMode="decimal"
            aria-label="amount billed in USDC"
            placeholder="0.02"
            value={billed}
            spellCheck={false}
            onChange={(e) => onBilled(e.target.value)}
            style={{ width: 140 }}
          />
        </label>
        <label className="label">
          <Ed x={`How much you bought, in ${unit.replace("$/", "")}`} p="How much you bought" />
          <br />
          <input
            type="text"
            inputMode="decimal"
            aria-label="quantity bought"
            placeholder="10"
            value={quantity}
            spellCheck={false}
            onChange={(e) => onQuantity(e.target.value)}
            style={{ width: 140 }}
          />
        </label>
        <label className="label">
          <Ed x="Who billed you, optionally" p="Who sent the bill. You can skip this" />
          <br />
          <input
            type="text"
            className="mono"
            aria-label="vendor address, optional"
            placeholder="0x…"
            value={vendor}
            spellCheck={false}
            onChange={(e) => onVendor(e.target.value)}
            style={{ width: 260 }}
          />
        </label>
      </div>

      <div className="btn-row">
        <button type="submit" className="btn" disabled={busy}>
          {busy ? (
            <Ed x="Pricing…" p="Checking…" />
          ) : (
            <Ed x="Price this bill" p="Check this bill" />
          )}
        </button>
        {/* Named, because supplying an address changes the ANSWER rather than
            the labelling: the press benchmarks one of our own sellers against
            the fleet and a stranger against the market. */}
        <span className="muted" style={{ fontSize: 12 }}>
          <Ed
            x="Nothing is stored and no account is needed. The address only decides which prices you are compared against."
            p="Nothing is saved and you need no account."
          />
        </span>
      </div>

      {problem ? (
        <p className="standfirst" style={{ color: "var(--breach)" }}>
          {problem}
        </p>
      ) : null}
    </form>
  );
}

/** WHERE THE PRICES CAME FROM, and what shape that source is in.
 *
 *  Prominent rather than tucked away, because of a coupling a reader cannot
 *  see: `/par` hands the comparison to the FLEET's own quotes whenever the
 *  market basket is unusable or stale. So "we compared you to the market" and
 *  "we compared you to ourselves" are the same screen with one field
 *  different, and that field is this one. */
function Source({ c }: { c: ParCheck }) {
  const ok = c.basket.status === "ok";
  const fleet = c.benchmarked_against === "fleet";
  const asOf = c.basket.fetched_at
    ? new Date(c.basket.fetched_at * 1000).toISOString().slice(0, 10)
    : null;
  return (
    <div className="panel panel-pad">
      <div className="section-head">
        <h3>
          <Ed x="What you were compared against" p="Who we compared you to" />
        </h3>
        <span className={fleet ? "chip chip-gold" : "chip chip-teal"}>
          {fleet ? (
            <Ed x="our own sellers" p="our own sellers" />
          ) : (
            <Ed x="the open market" p="other companies" />
          )}
        </span>
      </div>
      {fleet ? (
        <p className="standfirst">
          <Ed
            x="These are prices from sellers this deployment operates, not independent ones. Disclosed rather than hidden, and a weaker comparison than the market basket."
            p="These prices are our own, not other companies'. That is a weaker check."
          />
        </p>
      ) : null}
      <div className="table-scroll">
        <table className="sheet">
          <tbody>
            <tr>
              <td>
                <Ed x="Basket" p="Price list" />
              </td>
              <td className="mono">{c.basket.index_id || "…"}</td>
            </tr>
            <tr>
              <td>
                <Ed x="Prices in it" p="How many prices" />
              </td>
              {/* n of m, never a percentage. ACR-INF reads 5 of 10 today, and
                  the shortfall is the number worth seeing. */}
              <td className="mono">
                {c.basket.rows} of {c.basket.requested}
              </td>
            </tr>
            <tr>
              <td>
                <Ed x="Measured" p="Read on" />
              </td>
              <td className="mono">{asOf ?? "…"}</td>
            </tr>
            <tr>
              <td>
                <Ed x="State" p="Is it usable?" />
              </td>
              <td className="mono">
                <span className={ok ? "chip chip-teal" : "chip chip-breach"}>
                  {c.basket.status}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <p className="standfirst">
        <Ed
          x={
            <>
              Every figure in this basket is a published list price with the page it came from,
              the date it was read and the exact line quoted. The whole dated file and the gap it
              opens against our own reference levels are committed here:{" "}
              <a className="section-link" href={GAP_URL} rel="noreferrer" target="_blank">
                anchors/GAP.md
              </a>
              .
            </>
          }
          p={
            <>
              Each price below links to the page it came from.{" "}
              <a className="section-link" href={GAP_URL} rel="noreferrer" target="_blank">
                The full list is here
              </a>
              .
            </>
          }
        />
      </p>
    </div>
  );
}

/** Every price the verdict was computed from, each one openable. */
function Comparison({ quotes }: { quotes: ParQuote[] }) {
  if (quotes.length === 0) {
    return (
      <p className="standfirst">
        <Ed
          x="No comparable prices were found for this unit, so nothing above is a benchmark."
          p="We found no prices to compare with, so there is no verdict."
        />
      </p>
    );
  }
  return (
    <div className="table-scroll">
      <table className="sheet">
        <thead>
          <tr>
            <th>
              <Ed x="Seller" p="Who" />
            </th>
            <th>
              <Ed x="Their price" p="Their price" />
            </th>
            <th>
              <Ed x="Source" p="Where it is from" />
            </th>
            <th>
              <Ed x="Check it" p="Go and look" />
            </th>
          </tr>
        </thead>
        <tbody>
          {quotes.map((q) => (
            <tr key={`${q.seller}-${q.price_usdc}`}>
              <td className="wrap">
                {q.label ?? q.seller}
                {q.label ? <div className="label mono">{q.seller}</div> : null}
                {/* Disclosed, never filtered: the subgraph's own standard is
                    that a reader discounts a first-party price themselves. */}
                {q.first_party ? (
                  <span className="chip chip-gold">
                    <Ed x="ours" p="ours" />
                  </span>
                ) : null}
              </td>
              <td className="mono num">{fmtUsd(q.price_usdc)}</td>
              <td className="mono">{q.source}</td>
              <td className="wrap">
                {q.url ? (
                  <>
                    <a className="section-link" href={q.url} rel="noreferrer" target="_blank">
                      {new URL(q.url).hostname}
                    </a>
                    {q.cite ? <div className="label mono">{q.cite}</div> : null}
                  </>
                ) : (
                  <span className="muted">
                    <Ed x="no published page" p="no page to open" />
                  </span>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

/** WHY there is no benchmark, when there is none.
 *
 *  `par.reason` mirrors the subgraph's `unbenchmarkedReason` on the principle
 *  that module states plainly: an absent benchmark says WHICH absence it is. A
 *  page that renders "no verdict" for all four causes is telling a reader who
 *  typed a correct bill that they did something wrong. */
function NoBenchmark({ reason, sellers }: { reason: string; sellers: number }) {
  const why: Record<string, { x: string; p: string }> = {
    NO_QUOTES: {
      x: "No published price was found for this unit at all, so there is nothing to compare against.",
      p: "We found no prices for this kind of work, so we cannot say.",
    },
    ONE_SELLER: {
      x: "Only one price was found. One offer is not a market, and comparing a price to itself would be a number pretending to be a measurement.",
      p: "We only found one price. One price is not a market, so we will not pretend.",
    },
    NO_INDEPENDENT_SELLER: {
      x: "Every price found belongs to a seller this deployment operates, so a comparison would be us grading ourselves.",
      p: "All the prices we found are our own, so this check would mean nothing.",
    },
    NO_QUANTITY: {
      x: "Without a quantity there is no per-unit price, and a whole bill cannot be compared with a rate.",
      p: "We need to know how much you bought before we can compare.",
    },
  };
  const copy = why[reason];
  return (
    <div className="panel panel-pad">
      <p className="standfirst">
        {copy ? (
          <Ed x={copy.x} p={copy.p} />
        ) : (
          <Ed
            x={`No benchmark is available for this bill. The engine's reason: ${reason || "unstated"}.`}
            p="We cannot check this bill against anything right now."
          />
        )}
      </p>
      <p className="label mono">
        {reason} · {sellers}{" "}
        <Ed x="independent price(s) found" p="prices found" />
      </p>
    </div>
  );
}

function Verdict({ c, requestPath }: { c: ParCheck; requestPath: string }) {
  const chip = rateChip(c.over_rate_bp, c.benchmarked_against, c.basket?.status);
  const unitPrice = c.quantity > 0 ? c.billed_usdc / c.quantity : null;
  // `available` is the boolean and `reason` is the explanation; the page needs
  // both to decide between a verdict and a stated absence, which is why
  // neither is exempt from the render ledger.
  if (!c.par.available) {
    return (
      <>
        <section className="section">
          <div className="section-head">
            <h2>
              <Ed x="No verdict, and why" p="We cannot answer, and why" />
            </h2>
            <span className="chip muted">
              <Ed x="unbenchmarked" p="no answer" />
            </span>
          </div>
          <NoBenchmark reason={c.par.reason} sellers={c.par.sellers} />
        </section>
        <section className="section">
          <div className="section-head">
            <h2>
              <Ed x="The evidence" p="Where the prices came from" />
            </h2>
          </div>
          <Source c={c} />
          <Comparison quotes={c.par.quotes} />
        </section>
      </>
    );
  }
  return (
    <>
      <section className="section">
        <div className="section-head">
          <h2>
            <Ed x="The verdict" p="The answer" />
          </h2>
          <span className={chip.cls}>
            <Ed x={chip.x} p={chip.p} />
          </span>
        </div>

        <div className="panel panel-pad">
          <div className="table-scroll">
            <table className="sheet">
              <tbody>
                <tr>
                  <td>
                    <Ed x="You paid, per unit" p="You paid, each" />
                  </td>
                  <td className="mono num">{fmtUsd(unitPrice)}</td>
                </tr>
                <tr>
                  <td>
                    <Ed x="The going rate" p="What others charge" />
                  </td>
                  <td className="mono num">{fmtUsd(c.par.par_usdc)}</td>
                </tr>
                <tr>
                  <td>
                    <Ed x="The cheapest observed" p="The cheapest we saw" />
                  </td>
                  {/* NAMED, not just priced. A cheapest figure with no seller
                      beside it is a number a reader has to take on trust, and
                      `best_source` is the half of it that decides whether the
                      saving is reachable at all: a market row names a model,
                      which is what makes it checkable and what makes it
                      unroutable. The press draws that distinction in its own
                      rule sentence, so the page draws it here. */}
                  <td className="mono num">
                    {fmtUsd(c.par.best_usdc)}
                    {c.par.best_seller ? (
                      <div className="label mono">
                        {c.par.best_seller}
                        {c.par.best_source ? ` · ${c.par.best_source}` : ""}
                      </div>
                    ) : null}
                  </td>
                </tr>
                {c.verdict.saving_usdc != null && Number(c.verdict.saving_usdc) > 0 ? (
                  <tr>
                    <td>
                      <Ed
                        x="What the cheapest would have cost you"
                        p="What the cheapest would have cost"
                      />
                    </td>
                    <td className="mono num">
                      {fmtUsd(c.billed_usdc - Number(c.verdict.saving_usdc))}
                      <div className="label">
                        <Ed
                          x={`a difference of ${fmtUsd(Number(c.verdict.saving_usdc))} on this bill`}
                          p={`${fmtUsd(Number(c.verdict.saving_usdc))} less than you paid`}
                        />
                      </div>
                    </td>
                  </tr>
                ) : null}
                <tr>
                  {/* THE NUMBER TO READ, and not the same thing as
                      `verdict.verdict`. That field reads "over_par" whenever
                      material money sits at the CHEAPEST row, so a bill at
                      exactly the market median comes back labelled over par
                      while this reads under 1 bp. Both behaviours are
                      asserted in the press's own tests; the engine keeps its
                      semantics and this surface states the rate. */}
                  <td>
                    <Ed x="Difference from the going rate" p="How far off you are" />
                  </td>
                  <td className="mono num">{fmtBp(c.over_rate_bp)}</td>
                </tr>
                <tr>
                  <td>
                    <Ed x="Prices compared" p="Prices used" />
                  </td>
                  {/* A count beside a count, never a share — /traction refuses
                      rates for the same reason. */}
                  <td className="mono">
                    {c.par.sellers}
                    {c.par.first_party_sellers > 0 ? (
                      <span className="label">
                        {" "}
                        · {c.par.first_party_sellers} ours
                      </span>
                    ) : null}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="section-head">
          <h2>
            <Ed x="What the agent would do" p="What our robot would do" />
          </h2>
          <span className="chip">{c.would.intent}</span>
        </div>
        <p className="standfirst standfirst-block">
          <Ed
            x="This is the real decision ladder run against your bill, not a separate opinion about it. Nothing is paid and nothing is signed."
            p="This is the same checklist our agent uses on real bills. Nothing is paid."
          />
        </p>
        <div className="panel panel-pad">
          <p className="standfirst">{c.would.rule}</p>
          {c.would.recommended_intent && c.would.recommended_intent !== c.would.intent ? (
            <p className="label">
              <Ed
                x={`It would escalate to a person, and recommend: ${c.would.recommended_intent}`}
                p={`It would ask a person, and suggest: ${c.would.recommended_intent}`}
              />
            </p>
          ) : null}
          {/* THE CAVEATS THE LADDER RECORDED ABOUT ITS OWN ANSWER, which on a
              public check is most often "no counterparty screen was offered
              for this decision". Rendered rather than dropped: a verdict that
              hides what it could not check is the shape of /traction folding
              "we could not screen" into "we caught nothing", which that page
              refuses to do.

              Divs rather than a list element, because this stylesheet defines
              no bare list selector and `coverage.test.ts` fails any that is not
              classed. Writing the tag name in THIS comment also failed it: that
              scanner reads the whole file, comments included. */}
          {c.would.notes.length > 0 ? (
            <div className="label">
              {c.would.notes.map((n) => (
                <div key={n}>· {n}</div>
              ))}
            </div>
          ) : null}
        </div>
      </section>

      <section className="section">
        <div className="section-head">
          <h2>
            <Ed x="The evidence" p="Where the prices came from" />
          </h2>
          <span className="label">{c.par.basis || "…"}</span>
        </div>
        <Source c={c} />
        <Comparison quotes={c.par.quotes} />
      </section>

      <section className="section">
        <div className="section-head">
          <h2>
            <Ed x="Run it yourself" p="Do it yourself" />
          </h2>
        </div>
        <p className="standfirst standfirst-block">
          <Ed
            x="The request your inputs produced. It is a public read with no key, so this line is the whole thing: paste it into a terminal and you get the same answer this page is showing."
            p="This is the exact request we just made. Paste it into a terminal to get the same answer."
          />
        </p>
        <div className="panel panel-pad console-req">
          <span className="mono muted">GET</span>{" "}
          <span className="mono">{requestPath}</span>
        </div>
      </section>
    </>
  );
}

export function CheckView() {
  const [unit, setUnit] = useState<Unit>("$/1k tokens");
  const [billed, setBilled] = useState("");
  const [quantity, setQuantity] = useState("");
  const [vendor, setVendor] = useState("");
  const [problem, setProblem] = useState<string | null>(null);
  const [query, setQuery] = useState<string | null>(null);

  const { check, error, loading } = useParCheck(query);
  const c = check?.data ?? null;

  /* A LINKED RESULT MUST SURVIVE A RELOAD, so the URL is the source on mount —
     the same contract /tape keeps for `?payer=`. Everything is re-validated on
     the way back in: a hand-edited URL cannot poison state, it just does not
     load. Plain `history.replaceState` rather than the router, because this is
     one page's own address and a navigation would remount the form.

     `react-hooks/set-state-in-effect` warns here and the warning is accepted,
     as it is at `app/tape/view.tsx`: `window.location` does not exist during
     SSR, so state seeded from the address cannot be an initializer. It runs
     once, on mount, and bails before touching state unless every field
     validates. */
  useEffect(() => {
    const q = new URLSearchParams(window.location.search);
    const u = q.get("unit") ?? "";
    const b = Number(q.get("billed_usdc"));
    const n = Number(q.get("quantity"));
    const v = (q.get("vendor") ?? "").trim();
    if (!isUnit(u) || !Number.isFinite(b) || b <= 0 || !Number.isFinite(n) || n <= 0) return;
    if (v && !ADDRESS.test(v)) return;
    setUnit(u);
    setBilled(String(b));
    setQuantity(String(n));
    setVendor(v);
    setQuery(build(u, b, n, v));
  }, []);

  function build(u: string, b: number, n: number, v: string): string {
    const p = new URLSearchParams({
      unit: u,
      billed_usdc: String(b),
      quantity: String(n),
    });
    if (v) p.set("vendor", v);
    return p.toString();
  }

  function submit() {
    const b = Number(billed.trim());
    const n = Number(quantity.trim());
    const v = vendor.trim();
    if (!Number.isFinite(b) || b <= 0) {
      setProblem("The billed amount has to be a number above zero.");
      return;
    }
    if (!Number.isFinite(n) || n <= 0) {
      setProblem("The quantity has to be a number above zero.");
      return;
    }
    if (v && !ADDRESS.test(v)) {
      setProblem("That is not an address. It needs 0x and 40 characters, or leave it empty.");
      return;
    }
    setProblem(null);
    const q = build(unit, b, n, v);
    setQuery(q);
    const url = new URL(window.location.href);
    url.search = q;
    window.history.replaceState(null, "", url.toString());
  }

  // What the press was actually asked, reconstructed for display from the same
  // parts the proxy forwards. Shown rather than described, because the point of
  // the section is that a reader can run it.
  const requestPath = query
    ? `/par?${query.replace(/%2F/g, "%2F")}`
    : "";

  return (
    <>
      <section className="section">
        <div className="section-head">
          <h2>
            <Ed x="Check a bill" p="Is this bill fair?" />
          </h2>
          <span className="label">{INDEX_FOR_UNIT[unit]}</span>
        </div>
        <p className="standfirst standfirst-block">
          <Ed
            x="Give it one invoice and it answers against published list prices from sellers we do not operate, with a link to every price it used. No account, no key, nothing stored."
            p="Type in one bill. We compare it to real published prices and show you every one we used."
          />
        </p>
        <div className="panel panel-pad">
          <Form
            unit={unit}
            billed={billed}
            quantity={quantity}
            vendor={vendor}
            onUnit={(u) => {
              setUnit(u);
              setProblem(null);
            }}
            onBilled={(v) => {
              setBilled(v);
              setProblem(null);
            }}
            onQuantity={(v) => {
              setQuantity(v);
              setProblem(null);
            }}
            onVendor={(v) => {
              setVendor(v);
              setProblem(null);
            }}
            onSubmit={submit}
            problem={problem}
            busy={loading}
          />
        </div>
      </section>

      {/* THREE STATES, not two, and the middle one is the press being down.
          /spend spent weeks telling readers a business did not exist because
          its proxy could not distinguish "nothing" from "we could not ask".
          The same distinction is drawn here from the start: a 422 is a problem
          with the bill, a 503 is a problem with us, and neither is a verdict. */}
      {error && !c ? (
        <section className="section">
          <div className="panel panel-pad">
            <p className="standfirst">
              {error.status === 422 ? (
                <Ed
                  x="That bill could not be read, so nothing was priced. Check the amount and the quantity."
                  p="We could not read that bill, so we priced nothing. Check the numbers."
                />
              ) : null}
            </p>
            {/* A DEAD END UNTIL NOW, on the surface that most needed a way out.
                This page hand-rolled its own absent sentence while /spend and
                /traction used `WhyEmpty` — so a stranger arriving with a bill,
                on the default chain, where /par does not exist, was told the
                truth and given nowhere to go. `WhyEmpty` carries the switch.
                The 422 above stays its own branch: a bill we could not read is
                a fact about the bill, and no chain change fixes it. */}
            {error.status !== 422 ? (
              <WhyEmpty
                upstream={error.upstream}
                what="this benchmark"
                plainWhat="the price check"
              />
            ) : null}
          </div>
        </section>
      ) : null}

      {c ? <Verdict c={c} requestPath={requestPath} /> : null}
    </>
  );
}
