#!/usr/bin/env python3
"""Render the pitch deck from its one source.

`docs/pitch/deck.html` is body-content only, because that is what the Artifact
host wants: it supplies the doctype, head and body itself. A judge opening the
file from a clone, and Chrome printing it to PDF, both want the wrapper. So
this script owns the wrapper and nothing else does:

    docs/pitch/deck.html  ──►  docs/pitch/index.html   (standalone, openable)
                          ──►  docs/pitch.pdf          (8 pages, 16:9)

Nothing is copied by hand, so the three can never disagree. Edit deck.html and
re-run `make pitch`.

Chrome is the renderer rather than a Python PDF library because the deck's
layout is container queries and `@page`, and only a browser implements those —
`make deck` uses the same trick through marp-cli. If Chrome is missing this
exits non-zero rather than leaving yesterday's PDF sitting next to today's HTML
looking current.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

#: How long to give Chrome to produce the PDF before giving up on it.
TIMEOUT_S = 90.0

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "pitch" / "deck.html"
HTML = ROOT / "docs" / "pitch" / "index.html"
PDF = ROOT / "docs" / "pitch.pdf"
#: The demo teleprompter rides the same convention: body-content source for the
#: Artifact, wrapped copy for a clone. No PDF — it is a page you scroll and
#: click, not a deck you export.
VIDEO_SRC = ROOT / "docs" / "pitch" / "video.html"
VIDEO_HTML = ROOT / "docs" / "pitch" / "teleprompter.html"
#: The submission brief: the nine form fields, answered in order. This one IS
#: a PDF deliverable — A4 portrait, attached to the form — so it takes the
#: same Chrome pass as the deck.
BRIEF_SRC = ROOT / "docs" / "pitch" / "brief.html"
BRIEF_HTML = ROOT / "docs" / "pitch" / "submission-brief.html"
BRIEF_PDF = ROOT / "docs" / "submission-brief.pdf"

#: Where Chrome lives, in the order worth trying. `shutil.which` first so a
#: Linux CI box or a PATH-installed Chromium works without touching this list.
CHROME_CANDIDATES = (
    "google-chrome",
    "google-chrome-stable",
    "chromium",
    "chromium-browser",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
)

BANNER = (
    "<!-- GENERATED by scripts/build_pitch.py from docs/pitch/deck.html — do not edit.\n"
    "     Edit the source and re-run `make pitch`. -->\n"
)


def find_chrome() -> str | None:
    for c in CHROME_CANDIDATES:
        found = shutil.which(c) if "/" not in c else (c if Path(c).exists() else None)
        if found:
            return found
    return None


def wrap(body: str) -> str:
    """Lift the source's <title> into a real <head> and wrap the rest.

    The title has to *move* rather than be duplicated: left in the body it
    would render as visible text in a standalone page, which is exactly the
    kind of difference between the two outputs this script exists to prevent.
    """
    m = re.search(r"<title>(.*?)</title>\s*", body, re.S)
    title = m.group(1).strip() if m else "ACR — Arc Compute Rate"
    if m:
        body = body[: m.start()] + body[m.end() :]
    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8" />\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1" />\n'
        f"<title>{title}</title>\n"
        "</head>\n"
        "<body>\n"
        f"{BANNER}{body.lstrip()}\n"
        "</body>\n"
        "</html>\n"
    )


def print_pdf(chrome: str, html: Path, pdf: Path) -> bool:
    """Print one wrapped page to PDF with headless Chrome.

    Waits on the FILE, not on the process: Chrome writes the PDF in a few
    seconds and then keeps running — measured here in both --headless and
    --headless=new, so this is not a mode you can switch out of. Waiting for
    exit means waiting for the timeout on every successful build.
    """
    # Delete first, so "the file exists" below means *this* run produced it
    # and not that the last one did.
    pdf.unlink(missing_ok=True)

    # A throwaway profile: Chrome refuses to run headless against a profile
    # the user already has open, which is the normal state on a laptop mid-demo.
    with tempfile.TemporaryDirectory() as profile:
        proc = subprocess.Popen(
            [
                chrome,
                "--headless",
                "--disable-gpu",
                "--no-pdf-header-footer",
                "--no-first-run",
                "--no-default-browser-check",
                "--disable-background-networking",
                "--disable-extensions",
                f"--user-data-dir={profile}",
                f"--print-to-pdf={pdf}",
                html.as_uri(),
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )

        deadline = time.monotonic() + TIMEOUT_S
        size = -1
        while time.monotonic() < deadline:
            if proc.poll() is not None:
                break
            if pdf.exists():
                now = pdf.stat().st_size
                if now > 0 and now == size:
                    break  # written, and no longer growing
                size = now
            time.sleep(0.4)

        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()

    if not pdf.exists() or pdf.stat().st_size == 0:
        err = (proc.stderr.read() if proc.stderr else "") or "(no stderr)"
        print(f"pitch: Chrome wrote no PDF for {html.name}\n{err[-1500:]}", file=sys.stderr)
        return False

    print(f"  ✓ {pdf.relative_to(ROOT)}  ({pdf.stat().st_size / 1024:.0f} KB)")
    return True


def main() -> int:
    if not SRC.exists():
        print(f"pitch: {SRC.relative_to(ROOT)} is missing", file=sys.stderr)
        return 1

    HTML.write_text(wrap(SRC.read_text()))
    print(f"  ✓ {HTML.relative_to(ROOT)}  ({HTML.stat().st_size / 1024:.0f} KB)")

    if VIDEO_SRC.exists():
        VIDEO_HTML.write_text(wrap(VIDEO_SRC.read_text()))
        print(f"  ✓ {VIDEO_HTML.relative_to(ROOT)}  ({VIDEO_HTML.stat().st_size / 1024:.0f} KB)")

    if BRIEF_SRC.exists():
        BRIEF_HTML.write_text(wrap(BRIEF_SRC.read_text()))
        print(f"  ✓ {BRIEF_HTML.relative_to(ROOT)}  ({BRIEF_HTML.stat().st_size / 1024:.0f} KB)")

    chrome = find_chrome()
    if not chrome:
        print(
            "pitch: no Chrome/Chromium/Edge found — the HTML is written but the PDFs are not.\n"
            "       Install one, or open the HTML and print to PDF (deck 13.333in × 7.5in, brief A4).",
            file=sys.stderr,
        )
        return 1

    ok = print_pdf(chrome, HTML, PDF)
    if BRIEF_SRC.exists():
        ok = print_pdf(chrome, BRIEF_HTML, BRIEF_PDF) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
